// apps/web/src/components/app-breadcrumbs.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { BreadCrumb } from "primereact/breadcrumb";
import type { MenuItem } from "primereact/menuitem";

const itemTemplate = (item: MenuItem) =>
  item.url ? (
    <Link
      href={item.url}
      className="p-breadcrumb-item-link cursor-pointer text-sm"
    >
      <span>{item.label}</span>
    </Link>
  ) : (
    <span className="text-sm">{item.label}</span>
  );

function buildItems(pathname: string): MenuItem[] {
  if (pathname === "/library") return [];
  if (pathname === "/books/search") {
    return [
      { label: "Library", url: "/library", template: itemTemplate },
      { label: "Add books", template: itemTemplate },
    ];
  }
  if (pathname.startsWith("/books/")) {
    return [
      { label: "Library", url: "/library", template: itemTemplate },
      { label: "Book", template: itemTemplate },
    ];
  }
  if (pathname === "/settings") {
    return [
      { label: "Library", url: "/library", template: itemTemplate },
      { label: "Settings", template: itemTemplate },
    ];
  }
  return [];
}

export function AppBreadcrumbs() {
  const pathname = usePathname();
  const items = buildItems(pathname);

  if (items.length === 0) return null;

  return (
    <BreadCrumb
      data-test="breadcrumbs"
      className="bg-transparent p-0"
      model={items}
      home={undefined}
    />
  );
}

// apps/web/app/components/shell/AppBreadcrumbs.vue
<template>
  <Breadcrumb class="bg-transparent p-0" :home="home" :model="items">
    <template #item="{ item, props }">
      <NuxtLink v-if="item.to" :to="item.to" class="p-breadcrumb-item-link cursor-pointer">
        <span v-if="item.icon" :class="item.icon" aria-hidden="true" />
        <span v-else class="text-sm">{{ item.label }}</span>
      </NuxtLink>
      <span v-else v-bind="props.action" class="text-sm">{{ item.label }}</span>
    </template>
  </Breadcrumb>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from '#imports';

type BreadcrumbItem = { label?: string; icon?: string; to?: string };

const route = useRoute();

// Library is treated as the home destination, so we avoid a separate Home crumb.
const home = computed<BreadcrumbItem | undefined>(() => undefined);

const items = computed<BreadcrumbItem[]>(() => {
  const path = route.path || '/';
  if (path === '/library') {
    return [];
  }
  if (path === '/books/search') {
    return [{ label: 'Library', to: '/library' }, { label: 'Add books' }];
  }
  if (path.startsWith('/books/')) {
    return [{ label: 'Library', to: '/library' }, { label: 'Book' }];
  }
  if (path === '/settings') {
    return [{ label: 'Library', to: '/library' }, { label: 'Settings' }];
  }
  return [];
});
</script>
