// apps/web/src/components/app-topbar-book-search.tsx
"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { Button } from "primereact/button";
import { Card } from "primereact/card";
import { Dialog } from "primereact/dialog";
import { InputText } from "primereact/inputtext";
import { Message } from "primereact/message";
import { SelectButton } from "primereact/selectbutton";
import { Skeleton } from "primereact/skeleton";
import { ApiClientError, apiRequest } from "@/lib/api";
import { createBrowserClient } from "@/lib/supabase/browser";

type SearchScope = "my" | "global" | "both";

type LibrarySearchItem = {
  kind: "library";
  work_id: string;
  work_title: string;
  author_names: string[];
  cover_url: string | null;
  openlibrary_work_key: string | null;
};

type ExternalSearchItem = {
  kind: "openlibrary" | "googlebooks";
  source: "openlibrary" | "googlebooks";
  source_id: string;
  work_key: string;
  title: string;
  author_names: string[];
  cover_url: string | null;
  attribution?: { text: string; url: string | null } | null;
};

type SearchOption = LibrarySearchItem | ExternalSearchItem;

const LIBRARY_UPDATED_EVENT = "chapterverse:library-updated";

function itemKey(item: SearchOption): string {
  return item.kind === "library"
    ? `lib:${item.work_id}`
    : `ext:${item.work_key}`;
}

function displayTitle(item: SearchOption): string {
  return item.kind === "library" ? item.work_title : item.title;
}

function displayAuthors(item: SearchOption): string {
  return (item.author_names ?? []).join(", ") || "Unknown author";
}

export function AppTopBarBookSearch() {
  const router = useRouter();
  const supabase = useMemo(() => createBrowserClient(), []);

  const [query, setQuery] = useState("");
  const [scope, setScope] = useState<SearchScope>("both");
  const [languageFilter, setLanguageFilter] = useState("");
  const [yearFromFilter, setYearFromFilter] = useState("");
  const [yearToFilter, setYearToFilter] = useState("");

  const [mobileOpen, setMobileOpen] = useState(false);
  const [desktopOpen, setDesktopOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  const [libraryItems, setLibraryItems] = useState<LibrarySearchItem[]>([]);
  const [externalItems, setExternalItems] = useState<ExternalSearchItem[]>([]);
  const [addingKeys, setAddingKeys] = useState<Set<string>>(new Set());
  const [addedKeys, setAddedKeys] = useState<Set<string>>(new Set());

  const requestSeqRef = useRef(0);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const scopeOptions = useMemo(
    () => [
      { label: "My Library", value: "my" },
      { label: "Global", value: "global" },
      { label: "Both", value: "both" },
    ],
    [],
  );

  const visibleItems = useMemo(() => {
    const items: SearchOption[] = [];
    if (scope === "my" || scope === "both") {
      items.push(...libraryItems);
    }
    if (scope === "global" || scope === "both") {
      items.push(...externalItems);
    }
    return items.slice(0, 9);
  }, [externalItems, libraryItems, scope]);

  const clearTimer = () => {
    if (timerRef.current) {
      clearTimeout(timerRef.current);
      timerRef.current = null;
    }
  };

  const resetResults = () => {
    setLibraryItems([]);
    setExternalItems([]);
  };

  const clear = () => {
    setQuery("");
    setErrorMessage("");
    setLoading(false);
    resetResults();
    clearTimer();
    setDesktopOpen(false);
  };

  const runSearch = useCallback(
    async (trimmed: string) => {
      const seq = ++requestSeqRef.current;
      setLoading(true);
      setErrorMessage("");
      if (!mobileOpen) {
        setDesktopOpen(true);
      }

      try {
        let nextLibrary: LibrarySearchItem[] = [];
        let nextExternal: ExternalSearchItem[] = [];

        if (scope === "my" || scope === "both") {
          const payload = await apiRequest<{
            items: Omit<LibrarySearchItem, "kind">[];
          }>(supabase, "/api/v1/library/search", {
            query: { query: trimmed, limit: 10 },
          });
          if (seq !== requestSeqRef.current) return;
          nextLibrary = payload.items.map((item) => ({
            kind: "library",
            ...item,
          }));
        }

        const libraryKeys = new Set(
          nextLibrary
            .map((item) => item.openlibrary_work_key)
            .filter((item): item is string => Boolean(item)),
        );

        if (scope === "global" || scope === "both") {
          const params: Record<string, string | number> = {
            query: trimmed,
            limit: 10,
            page: 1,
          };
          const language = languageFilter.trim();
          const from = Number.parseInt(yearFromFilter.trim(), 10);
          const to = Number.parseInt(yearToFilter.trim(), 10);
          if (language) params.language = language;
          if (!Number.isNaN(from)) params.first_publish_year_from = from;
          if (!Number.isNaN(to)) params.first_publish_year_to = to;

          const payload = await apiRequest<{
            items: Array<{
              source?: string;
              source_id?: string;
              work_key: string;
              title: string;
              author_names?: string[];
              cover_url?: string | null;
              attribution?: { text?: unknown; url?: unknown } | null;
            }>;
          }>(supabase, "/api/v1/books/search", { query: params });
          if (seq !== requestSeqRef.current) return;

          nextExternal = payload.items
            .map((item) => {
              const source =
                item.source === "googlebooks" ? "googlebooks" : "openlibrary";
              const sourceId =
                typeof item.source_id === "string" &&
                item.source_id.trim().length > 0
                  ? item.source_id
                  : source === "openlibrary"
                    ? item.work_key
                    : item.work_key.replace(/^googlebooks:/, "");

              return {
                kind: source,
                source,
                source_id: sourceId,
                work_key:
                  source === "openlibrary"
                    ? item.work_key
                    : item.work_key || `googlebooks:${sourceId}`,
                title: item.title,
                author_names: item.author_names ?? [],
                cover_url: item.cover_url ?? null,
                attribution:
                  source === "googlebooks" &&
                  item.attribution &&
                  typeof item.attribution.text === "string"
                    ? {
                        text: item.attribution.text,
                        url:
                          typeof item.attribution.url === "string"
                            ? item.attribution.url
                            : null,
                      }
                    : null,
              } satisfies ExternalSearchItem;
            })
            .filter((item) =>
              scope === "both" ? !libraryKeys.has(item.work_key) : true,
            );
        }

        setLibraryItems(nextLibrary);
        setExternalItems(nextExternal);
      } catch (error) {
        if (seq !== requestSeqRef.current) return;
        resetResults();
        setErrorMessage(
          error instanceof ApiClientError
            ? error.message
            : "Unable to search right now.",
        );
      } finally {
        if (seq === requestSeqRef.current) {
          setLoading(false);
        }
      }
    },
    [languageFilter, mobileOpen, scope, supabase, yearFromFilter, yearToFilter],
  );

  const scheduleSearch = useCallback(
    (immediate: boolean) => {
      const trimmed = query.trim();
      if (trimmed.length < 2) {
        clearTimer();
        resetResults();
        setLoading(false);
        setErrorMessage("");
        setDesktopOpen(false);
        return;
      }

      clearTimer();
      if (immediate) {
        void runSearch(trimmed);
        return;
      }

      timerRef.current = setTimeout(() => {
        void runSearch(trimmed);
      }, 300);
    },
    [query, runSearch],
  );

  useEffect(() => {
    scheduleSearch(false);
    return () => clearTimer();
  }, [scheduleSearch]);

  useEffect(() => {
    scheduleSearch(true);
  }, [scope, languageFilter, yearFromFilter, yearToFilter, scheduleSearch]);

  const addOpenLibraryItem = async (item: ExternalSearchItem) => {
    if (addingKeys.has(item.work_key) || addedKeys.has(item.work_key)) {
      return;
    }

    setAddingKeys((current) => {
      const next = new Set(current);
      next.add(item.work_key);
      return next;
    });

    try {
      const imported = await apiRequest<{ work: { id: string } }>(
        supabase,
        "/api/v1/books/import",
        {
          method: "POST",
          body:
            item.source === "googlebooks"
              ? { source: "googlebooks", source_id: item.source_id }
              : { source: "openlibrary", work_key: item.work_key },
        },
      );

      await apiRequest<{ created: boolean }>(
        supabase,
        "/api/v1/library/items",
        {
          method: "POST",
          body: { work_id: imported.work.id, status: "to_read" },
        },
      );

      setAddedKeys((current) => {
        const next = new Set(current);
        next.add(item.work_key);
        return next;
      });
      window.dispatchEvent(new Event(LIBRARY_UPDATED_EVENT));
    } catch {
      setErrorMessage("Unable to add this book right now.");
    } finally {
      setAddingKeys((current) => {
        const next = new Set(current);
        next.delete(item.work_key);
        return next;
      });
    }
  };

  const openLibraryItem = (item: LibrarySearchItem) => {
    clear();
    setMobileOpen(false);
    router.push(`/books/${item.work_id}`);
  };

  const isDisabled = (item: SearchOption) =>
    item.kind !== "library" &&
    (addingKeys.has(item.work_key) || addedKeys.has(item.work_key));

  const renderResults = (mobile: boolean) => {
    if (errorMessage) {
      return (
        <Message
          severity="error"
          className="w-full"
          text={errorMessage}
          data-test={
            mobile ? "topbar-search-error-mobile" : "topbar-search-error"
          }
        />
      );
    }

    if (loading) {
      return (
        <div
          className="grid gap-2"
          data-test={
            mobile ? "topbar-search-loading-mobile" : "topbar-search-loading"
          }
        >
          {Array.from({ length: mobile ? 4 : 3 }).map((_, index) => (
            <Card key={index}>
              <div className="flex items-start gap-3">
                <Skeleton width="44px" height="64px" />
                <div className="flex-1">
                  <Skeleton width="70%" height="1rem" className="mb-2" />
                  <Skeleton width="45%" height="0.875rem" />
                </div>
              </div>
            </Card>
          ))}
        </div>
      );
    }

    if (!visibleItems.length) {
      return (
        <Message
          severity="info"
          className="w-full"
          text={
            query.trim().length < 2
              ? "Type at least 2 characters to search."
              : "No books found. Try another search."
          }
          data-test={
            mobile ? "topbar-search-hint-mobile" : "topbar-search-hint"
          }
        />
      );
    }

    return (
      <div
        className={`grid gap-3 ${
          mobile ? "grid-cols-2" : "grid-cols-3 items-start"
        }`}
        data-test={
          mobile ? "topbar-search-results-mobile" : "topbar-search-results"
        }
      >
        {visibleItems.map((item) => (
          <Card key={itemKey(item)} className="min-w-0">
            <Button
              text
              className="flex w-full min-w-0 items-start gap-3 text-left disabled:opacity-60"
              disabled={isDisabled(item)}
              data-test={
                mobile
                  ? item.kind === "library"
                    ? `topbar-search-open-mobile-${item.work_id}`
                    : `topbar-search-add-mobile-${item.work_key}`
                  : item.kind === "library"
                    ? `topbar-search-open-${item.work_id}`
                    : `topbar-search-add-${item.work_key}`
              }
              onClick={() => {
                if (item.kind === "library") {
                  openLibraryItem(item);
                  return;
                }
                void addOpenLibraryItem(item);
              }}
            >
              <div className="h-16 w-11 shrink-0 overflow-hidden rounded bg-[var(--p-surface-100)]">
                {item.cover_url ? (
                  <Image
                    src={item.cover_url}
                    alt=""
                    width={44}
                    height={64}
                    sizes="44px"
                    unoptimized
                    className="h-full w-full object-cover"
                  />
                ) : (
                  <div className="flex h-full w-full items-center justify-center text-xs text-[var(--p-text-muted-color)]">
                    No cover
                  </div>
                )}
              </div>
              <div className="min-w-0 flex-1">
                <p className="line-clamp-2 text-sm font-medium">
                  {displayTitle(item)}
                </p>
                <p className="line-clamp-2 text-xs text-[var(--p-text-muted-color)]">
                  {displayAuthors(item)}
                </p>
                {item.kind === "googlebooks" && item.attribution?.text ? (
                  <p className="mt-1 text-[10px] text-[var(--p-text-muted-color)]">
                    {item.attribution.text}
                  </p>
                ) : null}
              </div>
            </Button>
          </Card>
        ))}
      </div>
    );
  };

  return (
    <>
      <div
        className="absolute left-1/2 top-1/2 hidden -translate-x-1/2 -translate-y-1/2 lg:block"
        data-test="topbar-book-search-desktop"
      >
        <div className="flex w-[min(760px,92vw)] items-center gap-2 lg:w-[min(760px,52vw)]">
          <div className="flex flex-1">
            <div className="flex w-full items-center gap-1">
              <InputText
                value={query}
                onFocus={() => {
                  if (query.trim().length >= 2) {
                    setDesktopOpen(true);
                  }
                }}
                onBlur={(event) => {
                  // Close dropdown when focus leaves the entire search area.
                  const related = event.relatedTarget as Node | null;
                  const container = event.currentTarget.closest(
                    "[data-test='topbar-book-search-desktop']",
                  );
                  if (container && related && container.contains(related))
                    return;
                  // Delay slightly so click events on results fire first.
                  setTimeout(() => setDesktopOpen(false), 200);
                }}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Find a book"
                className="w-full"
                data-test="topbar-search-input"
              />
              {query.trim() ? (
                <Button
                  icon="pi pi-times"
                  text
                  severity="secondary"
                  size="small"
                  aria-label="Clear search"
                  data-test="topbar-search-clear"
                  onClick={clear}
                />
              ) : null}
            </div>
          </div>
          <SelectButton
            value={scope}
            options={scopeOptions}
            optionLabel="label"
            optionValue="value"
            data-test="topbar-search-scope"
            onChange={(event) => setScope(event.value as SearchScope)}
          />
        </div>

        {desktopOpen ? (
          <div
            className="absolute left-0 right-0 top-full z-50 mt-1 rounded-lg border border-[var(--surface-border)] bg-[var(--surface-overlay)] p-3 shadow-lg"
            data-test="topbar-search-popover"
          >
            <div className="mb-2 grid grid-cols-3 gap-2">
              <InputText
                value={languageFilter}
                onChange={(event) => setLanguageFilter(event.target.value)}
                placeholder="Lang (eng)"
                data-test="topbar-search-language"
              />
              <InputText
                value={yearFromFilter}
                onChange={(event) => setYearFromFilter(event.target.value)}
                placeholder="Year from"
                data-test="topbar-search-year-from"
              />
              <InputText
                value={yearToFilter}
                onChange={(event) => setYearToFilter(event.target.value)}
                placeholder="Year to"
                data-test="topbar-search-year-to"
              />
            </div>
            {renderResults(false)}
          </div>
        ) : null}
      </div>

      <Button
        text
        severity="secondary"
        className="lg:!hidden"
        icon="pi pi-search"
        aria-label="Search"
        data-test="topbar-search-mobile-open"
        onClick={() => setMobileOpen(true)}
      >
        Search
      </Button>

      {mobileOpen ? (
        <Dialog
          visible={mobileOpen}
          onHide={() => setMobileOpen(false)}
          header="Search"
          className="w-full max-w-xl"
          modal
          data-test="topbar-search-mobile-dialog"
        >
          <div className="w-full">
            <div className="mb-3">
              <div className="flex items-center gap-1">
                <InputText
                  value={query}
                  onChange={(event) => setQuery(event.target.value)}
                  placeholder="Find a book"
                  className="w-full"
                  data-test="topbar-search-input-mobile"
                />
                {query.trim() ? (
                  <Button
                    icon="pi pi-times"
                    text
                    severity="secondary"
                    size="small"
                    aria-label="Clear search"
                    data-test="topbar-search-clear-mobile"
                    onClick={clear}
                  />
                ) : null}
              </div>
            </div>

            <div className="mb-2 grid grid-cols-2 gap-2 sm:grid-cols-4">
              <SelectButton
                value={scope}
                options={scopeOptions}
                optionLabel="label"
                optionValue="value"
                data-test="topbar-search-scope-mobile"
                onChange={(event) => setScope(event.value as SearchScope)}
              />
              <InputText
                value={languageFilter}
                onChange={(event) => setLanguageFilter(event.target.value)}
                placeholder="Lang"
                data-test="topbar-search-language-mobile"
              />
              <InputText
                value={yearFromFilter}
                onChange={(event) => setYearFromFilter(event.target.value)}
                placeholder="Year from"
                data-test="topbar-search-year-from-mobile"
              />
              <InputText
                value={yearToFilter}
                onChange={(event) => setYearToFilter(event.target.value)}
                placeholder="Year to"
                data-test="topbar-search-year-to-mobile"
              />
            </div>

            {renderResults(true)}

            <div className="mt-3 flex justify-end">
              <Button
                outlined
                data-test="topbar-search-mobile-close"
                onClick={() => setMobileOpen(false)}
              >
                Close
              </Button>
            </div>
          </div>
        </Dialog>
      ) : null}
    </>
  );
}

// apps/web/app/components/shell/AppTopBarBookSearch.vue
<template>
  <div>
    <!-- Desktop: centered popover search -->
    <div
      v-show="!mobileOpen"
      class="absolute left-1/2 top-1/2 hidden -translate-x-1/2 -translate-y-1/2 md:block"
      data-test="topbar-book-search-desktop"
    >
      <div class="flex w-[min(760px,92vw)] items-center gap-2 lg:w-[min(760px,52vw)]">
        <div ref="anchorEl" class="relative flex flex-1 items-center">
          <InputText
            v-model="query"
            placeholder="Find a book"
            class="w-full pr-10"
            data-test="topbar-search-input"
            @focus="onFocus"
          />
          <Button
            v-if="query.trim().length"
            icon="pi pi-times"
            variant="text"
            severity="secondary"
            size="small"
            class="absolute right-1 top-1/2 -translate-y-1/2"
            aria-label="Clear search"
            data-test="topbar-search-clear"
            @click="clear"
          />
        </div>

        <SelectButton
          v-model="scope"
          :options="scopeOptions"
          optionLabel="label"
          optionValue="value"
          data-test="topbar-search-scope"
        />
      </div>
      <Popover
        ref="popoverRef"
        :dismissable="true"
        appendTo="body"
        data-test="topbar-search-popover"
      >
        <div class="w-[min(760px,92vw)] p-2 lg:w-[min(760px,52vw)]">
          <div class="mb-2 grid grid-cols-3 gap-2">
            <InputText
              v-model="languageFilter"
              class="w-full"
              placeholder="Lang (eng)"
              data-test="topbar-search-language"
            />
            <InputText
              v-model="yearFromFilter"
              class="w-full"
              placeholder="Year from"
              data-test="topbar-search-year-from"
            />
            <InputText
              v-model="yearToFilter"
              class="w-full"
              placeholder="Year to"
              data-test="topbar-search-year-to"
            />
          </div>

          <Message
            v-if="errorMessage"
            severity="error"
            :closable="false"
            class="mb-2"
            data-test="topbar-search-error"
          >
            {{ errorMessage }}
          </Message>

          <div
            v-if="loading"
            class="grid grid-cols-3 items-start gap-3"
            data-test="topbar-search-loading"
          >
            <Card v-for="n in 9" :key="n">
              <template #content>
                <div class="flex flex-col gap-3">
                  <Skeleton width="70%" height="1rem" />
                  <Skeleton width="45%" height="0.875rem" />
                  <Skeleton width="100%" height="2rem" />
                </div>
              </template>
            </Card>
          </div>

          <div
            v-else-if="visibleItems.length"
            class="grid grid-cols-3 items-start gap-3"
            data-test="topbar-search-results"
          >
            <div v-for="item in visibleItems" :key="itemKey(item)" class="min-w-0">
              <Fieldset
                :legend="desktopLegend(item)"
                :pt="{
                  root: {
                    class:
                      'min-w-0 h-full rounded-xl overflow-hidden border border-[var(--p-content-border-color)] !bg-transparent',
                  },
                  legendLabel: { class: 'text-xs font-medium tracking-wide' },
                  content: { class: 'min-w-0 p-0 !bg-transparent' },
                }"
              >
                <button
                  type="button"
                  class="flex min-w-0 w-full appearance-none items-start gap-3 border-0 bg-transparent px-3 py-2 text-left transition-colors hover:bg-black/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--p-primary-color)] dark:hover:bg-white/5"
                  :disabled="isTileDisabled(item)"
                  :data-test="
                    item.kind === 'library'
                      ? `topbar-search-open-${item.work_id}`
                      : `topbar-search-add-${item.work_key}`
                  "
                  @click="onDesktopTileClick(item)"
                >
                  <div
                    class="h-24 w-16 shrink-0 overflow-hidden rounded bg-black/5 dark:bg-white/5"
                  >
                    <img
                      v-if="item.cover_url"
                      :src="item.cover_url"
                      alt=""
                      class="h-full w-full object-cover"
                    />
                    <div v-else class="flex h-full w-full items-center justify-center">
                      <span class="pi pi-image text-xs text-[var(--p-text-muted-color)]" />
                    </div>
                  </div>
                  <div class="min-w-0 flex-1">
                    <p
                      class="m-0 overflow-hidden p-0 text-sm font-medium leading-snug [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:3]"
                    >
                      {{ item.kind === 'library' ? item.work_title : item.title }}
                    </p>
                    <p
                      class="m-0 mt-0.5 overflow-hidden p-0 text-xs leading-snug text-[var(--p-text-muted-color)] [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]"
                    >
                      {{ (item.author_names ?? []).join(', ') || 'Unknown author' }}
                    </p>
                    <p
                      v-if="item.kind !== 'library' && isAdding(item.work_key)"
                      class="m-0 mt-1 text-xs text-[var(--p-text-muted-color)]"
                    >
                      Adding...
                    </p>
                    <p
                      v-if="item.kind === 'googlebooks' && item.attribution?.text"
                      class="m-0 mt-1 text-[10px] text-[var(--p-text-muted-color)]"
                    >
                      {{ item.attribution.text }}
                    </p>
                  </div>
                </button>
              </Fieldset>
            </div>
          </div>

          <div
            v-else
            class="px-2 py-3 text-sm text-[var(--p-text-muted-color)]"
            data-test="topbar-search-hint"
          >
            {{
              query.trim().length < 2
                ? 'Type at least 2 characters to search.'
                : 'No books found. Try another search.'
            }}
          </div>
        </div>
      </Popover>
    </div>

    <!-- Mobile: button that opens a dialog -->
    <Button
      class="md:hidden"
      icon="pi pi-search"
      variant="text"
      severity="secondary"
      aria-label="Search"
      data-test="topbar-search-mobile-open"
      @click="openMobileDialog"
    />

    <Dialog
      v-model:visible="mobileOpen"
      header="Search"
      modal
      :dismissableMask="true"
      :draggable="false"
      :breakpoints="{ '640px': '95vw' }"
      style="width: 32rem"
      data-test="topbar-search-mobile-dialog"
    >
      <div class="flex flex-col gap-3">
        <div class="flex flex-col gap-2">
          <div class="relative flex items-center">
            <InputText
              v-model="query"
              placeholder="Find a book"
              class="w-full pr-10"
              data-test="topbar-search-input-mobile"
            />
            <Button
              v-if="query.trim().length"
              icon="pi pi-times"
              variant="text"
              severity="secondary"
              size="small"
              class="absolute right-1 top-1/2 -translate-y-1/2"
              aria-label="Clear search"
              data-test="topbar-search-clear-mobile"
              @click="clear"
            />
          </div>

          <SelectButton
            v-model="scope"
            :options="scopeOptions"
            optionLabel="label"
            optionValue="value"
            data-test="topbar-search-scope-mobile"
          />
          <div class="grid grid-cols-3 gap-2">
            <InputText
              v-model="languageFilter"
              placeholder="Lang"
              data-test="topbar-search-language-mobile"
            />
            <InputText
              v-model="yearFromFilter"
              placeholder="Year from"
              data-test="topbar-search-year-from-mobile"
            />
            <InputText
              v-model="yearToFilter"
              placeholder="Year to"
              data-test="topbar-search-year-to-mobile"
            />
          </div>
        </div>

        <Message
          v-if="errorMessage"
          severity="error"
          :closable="false"
          data-test="topbar-search-error-mobile"
        >
          {{ errorMessage }}
        </Message>

        <div v-if="loading" class="grid grid-cols-2 gap-3" data-test="topbar-search-loading-mobile">
          <Card v-for="n in 4" :key="n">
            <template #content>
              <div class="flex flex-col gap-3">
                <Skeleton width="70%" height="1rem" />
                <Skeleton width="45%" height="0.875rem" />
                <Skeleton width="100%" height="2rem" />
              </div>
            </template>
          </Card>
        </div>

        <div
          v-else-if="visibleItems.length"
          class="grid grid-cols-2 gap-3"
          data-test="topbar-search-results-mobile"
        >
          <div v-for="item in visibleItems" :key="itemKey(item)" class="min-w-0">
            <Fieldset
              :legend="desktopLegend(item)"
              :pt="{
                root: {
                  class:
                    'min-w-0 h-full rounded-xl overflow-hidden border border-[var(--p-content-border-color)] !bg-transparent',
                },
                legendLabel: { class: 'text-xs font-medium tracking-wide' },
                content: { class: 'min-w-0 p-0 !bg-transparent' },
              }"
            >
              <button
                type="button"
                class="flex min-w-0 w-full appearance-none items-start gap-3 border-0 bg-transparent px-3 py-2 text-left transition-colors hover:bg-black/5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--p-primary-color)] dark:hover:bg-white/5"
                :disabled="isTileDisabled(item)"
                :data-test="
                  item.kind === 'library'
                    ? `topbar-search-open-mobile-${item.work_id}`
                    : `topbar-search-add-mobile-${item.work_key}`
                "
                @click="onMobileTileClick(item)"
              >
                <div class="h-24 w-16 shrink-0 overflow-hidden rounded bg-black/5 dark:bg-white/5">
                  <img
                    v-if="item.cover_url"
                    :src="item.cover_url"
                    alt=""
                    class="h-full w-full object-cover"
                  />
                  <div v-else class="flex h-full w-full items-center justify-center">
                    <span class="pi pi-image text-xs text-[var(--p-text-muted-color)]" />
                  </div>
                </div>
                <div class="min-w-0 flex-1">
                  <p
                    class="m-0 overflow-hidden p-0 text-sm font-medium leading-snug [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:3]"
                  >
                    {{ item.kind === 'library' ? item.work_title : item.title }}
                  </p>
                  <p
                    class="m-0 mt-0.5 overflow-hidden p-0 text-xs leading-snug text-[var(--p-text-muted-color)] [display:-webkit-box] [-webkit-box-orient:vertical] [-webkit-line-clamp:2]"
                  >
                    {{ (item.author_names ?? []).join(', ') || 'Unknown author' }}
                  </p>
                  <p
                    v-if="item.kind !== 'library' && isAdding(item.work_key)"
                    class="m-0 mt-1 text-xs text-[var(--p-text-muted-color)]"
                  >
                    Adding...
                  </p>
                  <p
                    v-if="item.kind === 'googlebooks' && item.attribution?.text"
                    class="m-0 mt-1 text-[10px] text-[var(--p-text-muted-color)]"
                  >
                    {{ item.attribution.text }}
                  </p>
                </div>
              </button>
            </Fieldset>
          </div>
        </div>

        <div
          v-else
          class="text-sm text-[var(--p-text-muted-color)]"
          data-test="topbar-search-hint-mobile"
        >
          {{
            query.trim().length < 2
              ? 'Type at least 2 characters to search.'
              : 'No books found. Try another search.'
          }}
        </div>

        <div class="flex items-center justify-end">
          <Button
            label="Close"
            severity="secondary"
            variant="text"
            data-test="topbar-search-mobile-close"
            @click="mobileOpen = false"
          />
        </div>
      </div>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { navigateTo } from '#imports';
import Button from 'primevue/button';
import Card from 'primevue/card';
import Dialog from 'primevue/dialog';
import Fieldset from 'primevue/fieldset';
import InputText from 'primevue/inputtext';
import Message from 'primevue/message';
import Popover from 'primevue/popover';
import SelectButton from 'primevue/selectbutton';
import Skeleton from 'primevue/skeleton';
import { useToast } from 'primevue/usetoast';
import { ApiClientError, apiRequest } from '~/utils/api';

type LibrarySearchItem = {
  kind: 'library';
  work_id: string;
  work_title: string;
  author_names: string[];
  cover_url: string | null;
  openlibrary_work_key: string | null;
};

type OpenLibrarySearchItem = {
  kind: 'openlibrary';
  source: 'openlibrary';
  source_id: string;
  work_key: string;
  title: string;
  author_names: string[];
  cover_url: string | null;
  first_publish_year: number | null;
  edition_count?: number | null;
  languages?: string[];
  readable?: boolean;
  attribution?: null;
};

type GoogleBooksSearchItem = {
  kind: 'googlebooks';
  source: 'googlebooks';
  source_id: string;
  work_key: string;
  title: string;
  author_names: string[];
  cover_url: string | null;
  first_publish_year: number | null;
  edition_count?: number | null;
  languages?: string[];
  readable?: boolean;
  attribution?: { text: string; url: string | null } | null;
};

type ExternalSearchItem = OpenLibrarySearchItem | GoogleBooksSearchItem;
type SearchOption = LibrarySearchItem | ExternalSearchItem;
type SearchScope = 'my' | 'global' | 'both';
const LIBRARY_UPDATED_EVENT = 'chapterverse:library-updated';

const toast = useToast();

const mobileOpen = ref(false);
const query = ref('');
const scope = ref<SearchScope>('both');
const languageFilter = ref('');
const yearFromFilter = ref('');
const yearToFilter = ref('');
const scopeOptions = [
  { label: 'My Library', value: 'my' },
  { label: 'Global', value: 'global' },
  { label: 'Both', value: 'both' },
];

const popoverRef = ref<InstanceType<typeof Popover> | null>(null);
const anchorEl = ref<HTMLElement | null>(null);

const loading = ref(false);
const errorMessage = ref('');
const libraryItems = ref<LibrarySearchItem[]>([]);
const openLibraryItems = ref<ExternalSearchItem[]>([]);

const addedKeys = ref(new Set<string>());
const addingKeys = ref(new Set<string>());

let requestSeq = 0;
let searchTimer: ReturnType<typeof globalThis.setTimeout> | null = null;

const clearTimer = () => {
  if (searchTimer) {
    globalThis.clearTimeout(searchTimer);
    searchTimer = null;
  }
};

const visibleItems = computed<SearchOption[]>(() => {
  const items: SearchOption[] = [];
  if (scope.value === 'my' || scope.value === 'both') {
    items.push(...libraryItems.value);
  }
  if (scope.value === 'global' || scope.value === 'both') {
    items.push(...openLibraryItems.value);
  }
  return items.slice(0, 9);
});

const itemKey = (item: SearchOption) =>
  item.kind === 'library' ? `lib:${item.work_id}` : `ol:${item.work_key}`;

const openPopover = () => {
  if (mobileOpen.value) {
    return;
  }
  const target = anchorEl.value;
  if (!target) {
    return;
  }
  popoverRef.value?.show({ currentTarget: target } as any);
};

const hidePopover = () => {
  popoverRef.value?.hide();
};

const resetResults = () => {
  libraryItems.value = [];
  openLibraryItems.value = [];
};

const clear = () => {
  query.value = '';
  errorMessage.value = '';
  loading.value = false;
  resetResults();
  clearTimer();
  hidePopover();
};

const openMobileDialog = () => {
  hidePopover();
  mobileOpen.value = true;
};

const runSearch = async (trimmed: string) => {
  const currentSeq = ++requestSeq;
  loading.value = true;
  errorMessage.value = '';
  openPopover();

  try {
    let nextLibrary: LibrarySearchItem[] = [];
    let nextOpenLibrary: ExternalSearchItem[] = [];

    if (scope.value === 'my' || scope.value === 'both') {
      const payload = await apiRequest<{ items: Omit<LibrarySearchItem, 'kind'>[] }>(
        '/api/v1/library/search',
        { query: { query: trimmed, limit: 10 } },
      );
      if (currentSeq !== requestSeq) {
        return;
      }
      nextLibrary = payload.items.map((item) => ({ kind: 'library', ...item }));
    }

    const libraryKeys = new Set(
      nextLibrary.map((item) => item.openlibrary_work_key).filter(Boolean) as string[],
    );

    if (scope.value === 'global' || scope.value === 'both') {
      const parsedYearFrom = Number.parseInt(yearFromFilter.value.trim(), 10);
      const parsedYearTo = Number.parseInt(yearToFilter.value.trim(), 10);
      const queryParams: Record<string, string | number> = {
        query: trimmed,
        limit: 10,
        page: 1,
      };
      const language = languageFilter.value.trim();
      if (language) {
        queryParams.language = language;
      }
      if (!Number.isNaN(parsedYearFrom)) {
        queryParams.first_publish_year_from = parsedYearFrom;
      }
      if (!Number.isNaN(parsedYearTo)) {
        queryParams.first_publish_year_to = parsedYearTo;
      }
      const payload = await apiRequest<{
        items: Array<
          Omit<OpenLibrarySearchItem, 'kind' | 'source' | 'source_id'> & {
            source?: string;
            source_id?: string;
            attribution?: { text?: unknown; url?: unknown } | null;
          }
        >;
      }>('/api/v1/books/search', { query: queryParams });
      if (currentSeq !== requestSeq) {
        return;
      }
      nextOpenLibrary = payload.items
        .map((item) => {
          const source = item.source === 'googlebooks' ? 'googlebooks' : 'openlibrary';
          const sourceId =
            typeof item.source_id === 'string' && item.source_id.trim().length > 0
              ? item.source_id
              : source === 'openlibrary'
                ? item.work_key
                : item.work_key.replace(/^googlebooks:/, '');
          const base = {
            source,
            source_id: sourceId,
            work_key:
              source === 'openlibrary' ? item.work_key : item.work_key || `googlebooks:${sourceId}`,
            title: item.title,
            author_names: item.author_names ?? [],
            cover_url: item.cover_url ?? null,
            first_publish_year:
              typeof item.first_publish_year === 'number' ? item.first_publish_year : null,
            edition_count: typeof item.edition_count === 'number' ? item.edition_count : null,
            languages: Array.isArray(item.languages)
              ? item.languages.filter((value): value is string => typeof value === 'string')
              : [],
            readable: Boolean(item.readable),
          };
          if (source === 'googlebooks') {
            return {
              kind: 'googlebooks' as const,
              ...base,
              attribution:
                item.attribution &&
                typeof item.attribution.text === 'string' &&
                item.attribution.text.trim()
                  ? {
                      text: item.attribution.text.trim(),
                      url: typeof item.attribution.url === 'string' ? item.attribution.url : null,
                    }
                  : null,
            };
          }
          return {
            kind: 'openlibrary' as const,
            ...base,
            attribution: null,
          };
        })
        .filter((item) => (scope.value === 'both' ? !libraryKeys.has(item.work_key) : true));
    }

    libraryItems.value = nextLibrary;
    openLibraryItems.value = nextOpenLibrary;
  } catch (err) {
    if (currentSeq !== requestSeq) {
      return;
    }
    resetResults();
    errorMessage.value =
      err instanceof ApiClientError ? err.message : 'Unable to search right now.';
  } finally {
    if (currentSeq === requestSeq) {
      loading.value = false;
    }
  }
};

const scheduleSearch = (immediate: boolean) => {
  const trimmed = query.value.trim();
  if (trimmed.length < 2) {
    resetResults();
    errorMessage.value = '';
    loading.value = false;
    clearTimer();
    hidePopover();
    return;
  }

  clearTimer();
  if (immediate) {
    void runSearch(trimmed);
    return;
  }

  searchTimer = globalThis.setTimeout(() => {
    void runSearch(trimmed);
  }, 300);
};

watch(query, () => scheduleSearch(false));
watch(scope, () => scheduleSearch(true));
watch([languageFilter, yearFromFilter, yearToFilter], () => scheduleSearch(true));

const onFocus = () => {
  // Open the popover immediately when refocusing with an active query.
  if (query.value.trim().length >= 2) {
    openPopover();
  }
};

const isAdding = (workKey: string) => addingKeys.value.has(workKey);
const isAdded = (workKey: string) => addedKeys.value.has(workKey);
const isTileDisabled = (item: SearchOption) =>
  item.kind !== 'library' && (isAdding(item.work_key) || isAdded(item.work_key));

const desktopLegend = (item: SearchOption) => {
  if (item.kind === 'library') {
    return 'In Library';
  }
  if (isAdded(item.work_key)) {
    return 'Added';
  }
  return item.kind === 'googlebooks' ? 'Google Books' : 'Open Library';
};

const onDesktopTileClick = async (item: SearchOption) => {
  if (item.kind === 'library') {
    await openLibraryItem(item);
    return;
  }
  await addOpenLibraryItem(item);
};

const onMobileTileClick = async (item: SearchOption) => {
  await onDesktopTileClick(item);
};

const openLibraryItem = async (item: LibrarySearchItem) => {
  clear();
  mobileOpen.value = false;
  await navigateTo(`/books/${item.work_id}`);
};

const addOpenLibraryItem = async (item: ExternalSearchItem) => {
  if (isAdding(item.work_key) || isAdded(item.work_key)) {
    return;
  }

  addingKeys.value.add(item.work_key);
  addingKeys.value = new Set(addingKeys.value);
  try {
    const imported = await apiRequest<{ work: { id: string } }>('/api/v1/books/import', {
      method: 'POST',
      body:
        item.kind === 'googlebooks'
          ? { source: 'googlebooks', source_id: item.source_id }
          : { source: 'openlibrary', work_key: item.work_key },
    });
    const libraryResult = await apiRequest<{ created: boolean }>('/api/v1/library/items', {
      method: 'POST',
      body: { work_id: imported.work.id, status: 'to_read' },
    });

    addedKeys.value.add(item.work_key);
    addedKeys.value = new Set(addedKeys.value);
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event(LIBRARY_UPDATED_EVENT));
    }
    toast.add({
      severity: 'success',
      summary: libraryResult.created
        ? 'Book added to your library.'
        : 'Book is already in your library.',
      life: 2500,
    });
  } catch (err) {
    const msg = err instanceof ApiClientError ? err.message : 'Unable to add this book right now.';
    toast.add({ severity: 'error', summary: msg, life: 3000 });
  } finally {
    addingKeys.value.delete(item.work_key);
    addingKeys.value = new Set(addingKeys.value);
  }
};

onBeforeUnmount(() => {
  clearTimer();
});
</script>
