// apps/web/src/components/empty-state.tsx
import { Card } from "primereact/card";

interface EmptyStateProps {
  title: string;
  body?: string;
  icon?: string;
  "data-test"?: string;
  action?: React.ReactNode;
}

export function EmptyState({
  title,
  body,
  icon,
  "data-test": dataTest,
  action,
}: EmptyStateProps) {
  return (
    <Card data-test={dataTest}>
      <div className="flex items-start gap-4">
        {icon ? (
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--highlight-bg)] text-[var(--p-primary-color)]">
            <i className={icon} aria-hidden="true" />
          </div>
        ) : null}
        <div className="min-w-0">
          <p className="text-sm font-semibold">{title}</p>
          {body ? (
            <p className="mt-1 text-sm text-[var(--p-text-muted-color)]">
              {body}
            </p>
          ) : null}
          {action ? <div className="mt-4">{action}</div> : null}
        </div>
      </div>
    </Card>
  );
}

// apps/web/app/components/EmptyState.vue
<template>
  <div class="rounded-lg border border-slate-200/70 bg-white p-6" :data-test="dataTest">
    <div class="flex items-start gap-4">
      <div v-if="icon" class="rounded-full bg-slate-100 p-3 text-slate-600" aria-hidden="true">
        <i :class="icon"></i>
      </div>
      <div class="min-w-0">
        <p class="text-sm font-semibold text-slate-900">{{ title }}</p>
        <p v-if="body" class="mt-1 text-sm text-slate-600">
          {{ body }}
        </p>
        <div v-if="$slots.action" class="mt-4">
          <slot name="action" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
withDefaults(
  defineProps<{
    title: string;
    body?: string;
    icon?: string;
    dataTest?: string;
  }>(),
  { body: '', icon: '', dataTest: undefined },
);
</script>
